#!/bin/bash

# Create directories
mkdir -p "src/app/(routes)/dashboard/components"
mkdir -p "src/app/(routes)/jobs/[id]/components"
mkdir -p "src/app/(routes)/chat/components"
mkdir -p "src/app/api/jobs/[id]/stream"
mkdir -p "src/app/api/jobs/[id]/retry"
mkdir -p "src/app/api/jobs/[id]/cancel"
mkdir -p "src/app/api/jobs/[id]/export"
mkdir -p "src/app/api/jobs/import"
mkdir -p "src/app/api/items/[id]/stream"
mkdir -p "src/app/api/items/[id]/regenerate"
mkdir -p "src/app/api/items/[id]/chunks"
mkdir -p "src/app/api/items/bulk-retry"
mkdir -p "src/app/api/audio/chunks/[id]"
mkdir -p "src/app/api/audio/merge"
mkdir -p "src/app/api/audio/download/[id]"
mkdir -p "src/app/api/chat/[sessionId]/stream"
mkdir -p "src/app/api/chat/[sessionId]/tools"
mkdir -p "src/app/api/chat/sessions"
mkdir -p "src/app/api/voices/preview"
mkdir -p "src/app/api/settings/prompts"
mkdir -p "src/app/(routes)/settings"
mkdir -p "src/app/api/health"
mkdir -p "src/core/domain/entities"
mkdir -p "src/core/domain/value-objects"
mkdir -p "src/core/domain/events/base"
mkdir -p "src/core/domain/events/job"
mkdir -p "src/core/domain/events/item"
mkdir -p "src/core/domain/events/chunk"
mkdir -p "src/core/domain/events/error"
mkdir -p "src/core/domain/specifications"
mkdir -p "src/core/domain/use-cases/job"
mkdir -p "src/core/domain/use-cases/content"
mkdir -p "src/core/domain/use-cases/chat"
mkdir -p "src/core/domain/use-cases/voice"
mkdir -p "src/core/domain/use-cases/settings"
mkdir -p "src/core/ports/repositories"
mkdir -p "src/core/ports/services/ai"
mkdir -p "src/core/ports/services/tts"
mkdir -p "src/core/ports/services/storage"
mkdir -p "src/core/ports/services/audio"
mkdir -p "src/core/ports/services/parsing"
mkdir -p "src/core/ports/services/validation"
mkdir -p "src/core/ports/events"
mkdir -p "src/core/ports/queue"
mkdir -p "src/core/ports/streaming"
mkdir -p "src/infrastructure/database/prisma/migrations"
mkdir -p "src/infrastructure/database/repositories"
mkdir -p "src/infrastructure/services/ai/anthropic"
mkdir -p "src/infrastructure/services/ai/adapters"
mkdir -p "src/infrastructure/services/tts/elevenlabs"
mkdir -p "src/infrastructure/services/tts/adapters"
mkdir -p "src/infrastructure/services/storage/r2"
mkdir -p "src/infrastructure/services/storage/local"
mkdir -p "src/infrastructure/services/audio/ffmpeg"
mkdir -p "src/infrastructure/services/audio/utils"
mkdir -p "src/infrastructure/services/parsing/csv"
mkdir -p "src/infrastructure/services/parsing/text"
mkdir -p "src/infrastructure/services/parsing/validation"
mkdir -p "src/infrastructure/services/monitoring"
mkdir -p "src/infrastructure/queue/workers"
mkdir -p "src/infrastructure/queue/strategies"
mkdir -p "src/infrastructure/events/handlers"
mkdir -p "src/infrastructure/streaming/encoders"
mkdir -p "src/infrastructure/streaming/channels"
mkdir -p "src/infrastructure/cache"
mkdir -p "src/infrastructure/di/config"
mkdir -p "src/application/orchestrators"
mkdir -p "src/application/coordinators"
mkdir -p "src/application/workflows"
mkdir -p "src/application/services"
mkdir -p "src/application/dto/job"
mkdir -p "src/application/dto/item"
mkdir -p "src/application/dto/chat"
mkdir -p "src/application/dto/csv"
mkdir -p "src/application/mappers"
mkdir -p "src/presentation/components/features/csv-import"
mkdir -p "src/presentation/components/features/job-management"
mkdir -p "src/presentation/components/features/content-items"
mkdir -p "src/presentation/components/features/text-generation"
mkdir -p "src/presentation/components/features/audio-generation"
mkdir -p "src/presentation/components/features/chat-interface"
mkdir -p "src/presentation/components/features/error-management"
mkdir -p "src/presentation/components/features/settings"
mkdir -p "src/presentation/components/shared/ui"
mkdir -p "src/presentation/components/shared/layout"
mkdir -p "src/presentation/components/shared/feedback"
mkdir -p "src/presentation/components/shared/data"
mkdir -p "src/presentation/hooks/jobs"
mkdir -p "src/presentation/hooks/items"
mkdir -p "src/presentation/hooks/streaming"
mkdir -p "src/presentation/hooks/audio"
mkdir -p "src/presentation/hooks/chat"
mkdir -p "src/presentation/hooks/csv"
mkdir -p "src/presentation/hooks/shared"
mkdir -p "src/presentation/state/stores"
mkdir -p "src/presentation/state/queries"
mkdir -p "src/shared/types"
mkdir -p "src/shared/constants"
mkdir -p "src/shared/utils/validation"
mkdir -p "src/shared/utils/formatting"
mkdir -p "src/shared/utils/helpers"
mkdir -p "src/shared/utils/errors"
mkdir -p "src/shared/config"
mkdir -p "src/shared/lib"

# Create files
touch "src/app/(routes)/dashboard/page.tsx"
touch "src/app/(routes)/jobs/[id]/page.tsx"
touch "src/app/(routes)/jobs/page.tsx"
touch "src/app/(routes)/chat/page.tsx"
touch "src/app/(routes)/settings/page.tsx"
touch "src/app/api/jobs/route.ts"
touch "src/app/api/jobs/[id]/route.ts"
touch "src/app/api/jobs/[id]/stream/route.ts"
touch "src/app/api/jobs/[id]/retry/route.ts"
touch "src/app/api/jobs/[id]/cancel/route.ts"
touch "src/app/api/jobs/[id]/export/route.ts"
touch "src/app/api/jobs/import/route.ts"
touch "src/app/api/items/[id]/route.ts"
touch "src/app/api/items/[id]/stream/route.ts"
touch "src/app/api/items/[id]/regenerate/route.ts"
touch "src/app/api/items/[id]/chunks/route.ts"
touch "src/app/api/items/bulk-retry/route.ts"
touch "src/app/api/audio/chunks/[id]/route.ts"
touch "src/app/api/audio/merge/route.ts"
touch "src/app/api/audio/download/[id]/route.ts"
touch "src/app/api/chat/route.ts"
touch "src/app/api/chat/[sessionId]/route.ts"
touch "src/app/api/chat/[sessionId]/stream/route.ts"
touch "src/app/api/chat/[sessionId]/tools/route.ts"
touch "src/app/api/chat/sessions/route.ts"
touch "src/app/api/voices/route.ts"
touch "src/app/api/voices/preview/route.ts"
touch "src/app/api/settings/route.ts"
touch "src/app/api/settings/prompts/route.ts"
touch "src/app/api/health/route.ts"
touch "src/app/layout.tsx"
touch "src/core/domain/entities/Job.ts"
touch "src/core/domain/entities/ContentItem.ts"
touch "src/core/domain/entities/AudioChunk.ts"
touch "src/core/domain/entities/GeneratedText.ts"
touch "src/core/domain/entities/ErrorLog.ts"
touch "src/core/domain/entities/ChatSession.ts"
touch "src/core/domain/entities/ChatMessage.ts"
touch "src/core/domain/entities/UserSettings.ts"
touch "src/core/domain/value-objects/JobStatus.ts"
touch "src/core/domain/value-objects/ItemStatus.ts"
touch "src/core/domain/value-objects/ChunkStatus.ts"
touch "src/core/domain/value-objects/AudioConfig.ts"
touch "src/core/domain/value-objects/VoiceSettings.ts"
touch "src/core/domain/value-objects/PromptTemplate.ts"
touch "src/core/domain/value-objects/CSVRow.ts"
touch "src/core/domain/value-objects/TextChunk.ts"
touch "src/core/domain/value-objects/AudioMetadata.ts"
touch "src/core/domain/events/base/DomainEvent.ts"
touch "src/core/domain/events/base/EventMetadata.ts"
touch "src/core/domain/events/job/JobCreatedEvent.ts"
touch "src/core/domain/events/job/JobStartedEvent.ts"
touch "src/core/domain/events/job/JobProgressUpdatedEvent.ts"
touch "src/core/domain/events/job/JobCompletedEvent.ts"
touch "src/core/domain/events/job/JobFailedEvent.ts"
touch "src/core/domain/events/job/JobCancelledEvent.ts"
touch "src/core/domain/events/job/JobResumedEvent.ts"
touch "src/core/domain/events/item/ItemCreatedEvent.ts"
touch "src/core/domain/events/item/ItemValidationStartedEvent.ts"
touch "src/core/domain/events/item/ItemValidationCompletedEvent.ts"
touch "src/core/domain/events/item/TextGenerationStartedEvent.ts"
touch "src/core/domain/events/item/TextGenerationProgressEvent.ts"
touch "src/core/domain/events/item/TextGenerationCompletedEvent.ts"
touch "src/core/domain/events/item/TextRefinementStartedEvent.ts"
touch "src/core/domain/events/item/TextRefinementCompletedEvent.ts"
touch "src/core/domain/events/item/TextChunkingCompletedEvent.ts"
touch "src/core/domain/events/item/AudioGenerationStartedEvent.ts"
touch "src/core/domain/events/item/AudioChunkGeneratedEvent.ts"
touch "src/core/domain/events/item/AudioMergeStartedEvent.ts"
touch "src/core/domain/events/item/AudioMergeCompletedEvent.ts"
touch "src/core/domain/events/item/ItemCompletedEvent.ts"
touch "src/core/domain/events/item/ItemFailedEvent.ts"
touch "src/core/domain/events/chunk/ChunkCreatedEvent.ts"
touch "src/core/domain/events/chunk/ChunkProcessingStartedEvent.ts"
touch "src/core/domain/events/chunk/ChunkProcessingCompletedEvent.ts"
touch "src/core/domain/events/chunk/ChunkFailedEvent.ts"
touch "src/core/domain/events/error/ErrorOccurredEvent.ts"
touch "src/core/domain/events/error/RateLimitHitEvent.ts"
touch "src/core/domain/events/error/RetryScheduledEvent.ts"
touch "src/core/domain/specifications/CSVValidationSpec.ts"
touch "src/core/domain/specifications/TextLengthSpec.ts"
touch "src/core/domain/specifications/AudioDurationSpec.ts"
touch "src/core/domain/specifications/VoiceAvailabilitySpec.ts"
touch "src/core/domain/use-cases/job/CreateJobFromCSVUseCase.ts"
touch "src/core/domain/use-cases/job/StartJobProcessingUseCase.ts"
touch "src/core/domain/use-cases/job/PauseJobUseCase.ts"
touch "src/core/domain/use-cases/job/ResumeJobUseCase.ts"
touch "src/core/domain/use-cases/job/CancelJobUseCase.ts"
touch "src/core/domain/use-cases/job/RetryFailedJobItemsUseCase.ts"
touch "src/core/domain/use-cases/job/GetJobStatusUseCase.ts"
touch "src/core/domain/use-cases/job/ExportJobResultsUseCase.ts"
touch "src/core/domain/use-cases/job/DeleteJobUseCase.ts"
touch "src/core/domain/use-cases/content/ValidateContentItemUseCase.ts"
touch "src/core/domain/use-cases/content/GenerateTextUseCase.ts"
touch "src/core/domain/use-cases/content/RefineTextUseCase.ts"
touch "src/core/domain/use-cases/content/ChunkTextUseCase.ts"
touch "src/core/domain/use-cases/content/GenerateAudioForChunkUseCase.ts"
touch "src/core/domain/use-cases/content/GenerateAllChunksUseCase.ts"
touch "src/core/domain/use-cases/content/MergeAudioChunksUseCase.ts"
touch "src/core/domain/use-cases/content/UploadAudioUseCase.ts"
touch "src/core/domain/use-cases/content/RegenerateItemUseCase.ts"
touch "src/core/domain/use-cases/content/CancelItemProcessingUseCase.ts"
touch "src/core/domain/use-cases/chat/CreateChatSessionUseCase.ts"
touch "src/core/domain/use-cases/chat/SendMessageUseCase.ts"
touch "src/core/domain/use-cases/chat/StreamChatResponseUseCase.ts"
touch "src/core/domain/use-cases/chat/ExecuteToolCallUseCase.ts"
touch "src/core/domain/use-cases/chat/GetChatHistoryUseCase.ts"
touch "src/core/domain/use-cases/chat/SaveWorkspaceStateUseCase.ts"
touch "src/core/domain/use-cases/chat/DeleteChatSessionUseCase.ts"
touch "src/core/domain/use-cases/voice/ListAvailableVoicesUseCase.ts"
touch "src/core/domain/use-cases/voice/PreviewVoiceUseCase.ts"
touch "src/core/domain/use-cases/voice/ValidateVoiceIdUseCase.ts"
touch "src/core/domain/use-cases/settings/GetUserSettingsUseCase.ts"
touch "src/core/domain/use-cases/settings/UpdateUserSettingsUseCase.ts"
touch "src/core/domain/use-cases/settings/CreateCustomPromptUseCase.ts"
touch "src/core/domain/use-cases/settings/DeleteCustomPromptUseCase.ts"
touch "src/core/ports/repositories/IJobRepository.ts"
touch "src/core/ports/repositories/IContentItemRepository.ts"
touch "src/core/ports/repositories/IAudioChunkRepository.ts"
touch "src/core/ports/repositories/IGeneratedTextRepository.ts"
touch "src/core/ports/repositories/IErrorLogRepository.ts"
touch "src/core/ports/repositories/IChatSessionRepository.ts"
touch "src/core/ports/repositories/IChatMessageRepository.ts"
touch "src/core/ports/repositories/IUserSettingsRepository.ts"
touch "src/core/ports/services/ai/IAIService.ts"
touch "src/core/ports/services/ai/ITextGenerationService.ts"
touch "src/core/ports/services/ai/ITextRefinementService.ts"
touch "src/core/ports/services/ai/IChatService.ts"
touch "src/core/ports/services/tts/ITTSService.ts"
touch "src/core/ports/services/tts/IVoiceProviderService.ts"
touch "src/core/ports/services/storage/IStorageService.ts"
touch "src/core/ports/services/storage/IFileUploadService.ts"
touch "src/core/ports/services/storage/IFileDownloadService.ts"
touch "src/core/ports/services/audio/IAudioMergeService.ts"
touch "src/core/ports/services/audio/IAudioProcessingService.ts"
touch "src/core/ports/services/audio/IAudioMetadataService.ts"
touch "src/core/ports/services/parsing/ICSVParserService.ts"
touch "src/core/ports/services/parsing/ITextChunkerService.ts"
touch "src/core/ports/services/parsing/ITextNormalizerService.ts"
touch "src/core/ports/services/validation/IValidationService.ts"
touch "src/core/ports/services/validation/ISchemaValidatorService.ts"
touch "src/core/ports/events/IEventBus.ts"
touch "src/core/ports/events/IEventStore.ts"
touch "src/core/ports/events/IEventHandler.ts"
touch "src/core/ports/queue/IQueue.ts"
touch "src/core/ports/queue/IQueueManager.ts"
touch "src/core/ports/queue/IWorker.ts"
touch "src/core/ports/streaming/IStreamManager.ts"
touch "src/core/ports/streaming/ISSEService.ts"
touch "src/infrastructure/database/prisma/schema.prisma"
touch "src/infrastructure/database/prisma/seed.ts"
touch "src/infrastructure/database/repositories/PrismaJobRepository.ts"
touch "src/infrastructure/database/repositories/PrismaContentItemRepository.ts"
touch "src/infrastructure/database/repositories/PrismaAudioChunkRepository.ts"
touch "src/infrastructure/database/repositories/PrismaGeneratedTextRepository.ts"
touch "src/infrastructure/database/repositories/PrismaErrorLogRepository.ts"
touch "src/infrastructure/database/repositories/PrismaChatSessionRepository.ts"
touch "src/infrastructure/database/repositories/PrismaChatMessageRepository.ts"
touch "src/infrastructure/database/repositories/PrismaUserSettingsRepository.ts"
touch "src/infrastructure/services/ai/anthropic/AnthropicService.ts"
touch "src/infrastructure/services/ai/anthropic/StreamingService.ts"
touch "src/infrastructure/services/ai/anthropic/PromptBuilder.ts"
touch "src/infrastructure/services/ai/anthropic/ResponseParser.ts"
touch "src/infrastructure/services/ai/anthropic/RateLimiter.ts"
touch "src/infrastructure/services/ai/adapters/TextGenerationAdapter.ts"
touch "src/infrastructure/services/ai/adapters/TextRefinementAdapter.ts"
touch "src/infrastructure/services/ai/adapters/ChatAdapter.ts"
touch "src/infrastructure/services/tts/elevenlabs/ElevenLabsService.ts"
touch "src/infrastructure/services/tts/elevenlabs/VoiceManager.ts"
touch "src/infrastructure/services/tts/elevenlabs/AudioGenerator.ts"
touch "src/infrastructure/services/tts/elevenlabs/RateLimiter.ts"
touch "src/infrastructure/services/tts/adapters/TTSAdapter.ts"
touch "src/infrastructure/services/storage/r2/R2StorageService.ts"
touch "src/infrastructure/services/storage/r2/FileUploader.ts"
touch "src/infrastructure/services/storage/r2/FileDownloader.ts"
touch "src/infrastructure/services/storage/r2/URLGenerator.ts"
touch "src/infrastructure/services/storage/local/LocalStorageService.ts"
touch "src/infrastructure/services/audio/ffmpeg/FFmpegMergeService.ts"
touch "src/infrastructure/services/audio/ffmpeg/AudioProcessor.ts"
touch "src/infrastructure/services/audio/ffmpeg/MetadataExtractor.ts"
touch "src/infrastructure/services/audio/utils/AudioValidator.ts"
touch "src/infrastructure/services/audio/utils/AudioNormalizer.ts"
touch "src/infrastructure/services/parsing/csv/CSVParserService.ts"
touch "src/infrastructure/services/parsing/csv/CSVValidator.ts"
touch "src/infrastructure/services/parsing/csv/RowMapper.ts"
touch "src/infrastructure/services/parsing/csv/EncodingDetector.ts"
touch "src/infrastructure/services/parsing/text/SmartTextChunker.ts"
touch "src/infrastructure/services/parsing/text/SentenceSplitter.ts"
touch "src/infrastructure/services/parsing/text/CharacterCounter.ts"
touch "src/infrastructure/services/parsing/text/TextNormalizer.ts"
touch "src/infrastructure/services/parsing/validation/SchemaValidator.ts"
touch "src/infrastructure/services/parsing/validation/DataSanitizer.ts"
touch "src/infrastructure/services/parsing/validation/ConstraintChecker.ts"
touch "src/infrastructure/services/monitoring/LoggerService.ts"
touch "src/infrastructure/services/monitoring/MetricsCollector.ts"
touch "src/infrastructure/services/monitoring/ErrorTracker.ts"
touch "src/infrastructure/queue/QueueManager.ts"
touch "src/infrastructure/queue/RedisQueue.ts"
touch "src/infrastructure/queue/InMemoryQueue.ts"
touch "src/infrastructure/queue/workers/BaseWorker.ts"
touch "src/infrastructure/queue/workers/ValidationWorker.ts"
touch "src/infrastructure/queue/workers/TextGenerationWorker.ts"
touch "src/infrastructure/queue/workers/TextRefinementWorker.ts"
touch "src/infrastructure/queue/workers/TextChunkingWorker.ts"
touch "src/infrastructure/queue/workers/AudioGenerationWorker.ts"
touch "src/infrastructure/queue/workers/AudioMergeWorker.ts"
touch "src/infrastructure/queue/workers/UploadWorker.ts"
touch "src/infrastructure/queue/strategies/RetryStrategy.ts"
touch "src/infrastructure/queue/strategies/RateLimitStrategy.ts"
touch "src/infrastructure/queue/strategies/PriorityStrategy.ts"
touch "src/infrastructure/events/EventBus.ts"
touch "src/infrastructure/events/InMemoryEventBus.ts"
touch "src/infrastructure/events/EventStore.ts"
touch "src/infrastructure/events/handlers/JobEventHandlers.ts"
touch "src/infrastructure/events/handlers/ItemEventHandlers.ts"
touch "src/infrastructure/events/handlers/ErrorEventHandlers.ts"
touch "src/infrastructure/events/handlers/MetricsEventHandlers.ts"
touch "src/infrastructure/streaming/SSEManager.ts"
touch "src/infrastructure/streaming/StreamRegistry.ts"
touch "src/infrastructure/streaming/encoders/SSEEncoder.ts"
touch "src/infrastructure/streaming/encoders/JSONEncoder.ts"
touch "src/infrastructure/streaming/channels/JobChannel.ts"
touch "src/infrastructure/streaming/channels/ItemChannel.ts"
touch "src/infrastructure/streaming/channels/ChatChannel.ts"
touch "src/infrastructure/cache/CacheManager.ts"
touch "src/infrastructure/cache/RedisCache.ts"
touch "src/infrastructure/cache/InMemoryCache.ts"
touch "src/infrastructure/di/Container.ts"
touch "src/infrastructure/di/ServiceProvider.ts"
touch "src/infrastructure/di/config/repositories.config.ts"
touch "src/infrastructure/di/config/services.config.ts"
touch "src/infrastructure/di/config/usecases.config.ts"
touch "src/infrastructure/di/config/workers.config.ts"
touch "src/application/orchestrators/JobOrchestrator.ts"
touch "src/application/orchestrators/PipelineOrchestrator.ts"
touch "src/application/orchestrators/ChatOrchestrator.ts"
touch "src/application/coordinators/ItemProcessingCoordinator.ts"
touch "src/application/coordinators/ChunkProcessingCoordinator.ts"
touch "src/application/coordinators/ErrorRecoveryCoordinator.ts"
touch "src/application/workflows/CSVImportWorkflow.ts"
touch "src/application/workflows/TextGenerationWorkflow.ts"
touch "src/application/workflows/AudioGenerationWorkflow.ts"
touch "src/application/workflows/CompleteItemWorkflow.ts"
touch "src/application/services/ErrorRecoveryService.ts"
touch "src/application/services/ProgressTrackingService.ts"
touch "src/application/services/NotificationService.ts"
touch "src/application/services/HealthCheckService.ts"
touch "src/application/dto/job/CreateJobDTO.ts"
touch "src/application/dto/job/JobStatusDTO.ts"
touch "src/application/dto/job/JobProgressDTO.ts"
touch "src/application/dto/job/JobExportDTO.ts"
touch "src/application/dto/item/ContentItemDTO.ts"
touch "src/application/dto/item/ItemProgressDTO.ts"
touch "src/application/dto/item/ItemErrorDTO.ts"
touch "src/application/dto/chat/ChatMessageDTO.ts"
touch "src/application/dto/chat/ChatSessionDTO.ts"
touch "src/application/dto/chat/ToolCallDTO.ts"
touch "src/application/dto/csv/CSVRowDTO.ts"
touch "src/application/dto/csv/CSVValidationDTO.ts"
touch "src/application/mappers/JobMapper.ts"
touch "src/application/mappers/ContentItemMapper.ts"
touch "src/application/mappers/AudioChunkMapper.ts"
touch "src/application/mappers/ChatMapper.ts"
touch "src/application/mappers/ErrorMapper.ts"
touch "src/presentation/components/features/csv-import/CSVUploader.tsx"
touch "src/presentation/components/features/csv-import/CSVPreview.tsx"
touch "src/presentation/components/features/csv-import/ColumnMapper.tsx"
touch "src/presentation/components/features/csv-import/ValidationResults.tsx"
touch "src/presentation/components/features/csv-import/ImportProgress.tsx"
touch "src/presentation/components/features/job-management/JobList.tsx"
touch "src/presentation/components/features/job-management/JobCard.tsx"
touch "src/presentation/components/features/job-management/JobDetails.tsx"
touch "src/presentation/components/features/job-management/JobProgress.tsx"
touch "src/presentation/components/features/job-management/JobActions.tsx"
touch "src/presentation/components/features/job-management/JobFilters.tsx"
touch "src/presentation/components/features/content-items/ItemList.tsx"
touch "src/presentation/components/features/content-items/ItemCard.tsx"
touch "src/presentation/components/features/content-items/ItemDetails.tsx"
touch "src/presentation/components/features/content-items/ItemProgress.tsx"
touch "src/presentation/components/features/content-items/StatusBadge.tsx"
touch "src/presentation/components/features/content-items/ItemActions.tsx"
touch "src/presentation/components/features/text-generation/TextEditor.tsx"
touch "src/presentation/components/features/text-generation/StreamingTextDisplay.tsx"
touch "src/presentation/components/features/text-generation/TextRefinementPanel.tsx"
touch "src/presentation/components/features/text-generation/PromptSelector.tsx"
touch "src/presentation/components/features/text-generation/GenerationStats.tsx"
touch "src/presentation/components/features/audio-generation/AudioPlayer.tsx"
touch "src/presentation/components/features/audio-generation/WaveformVisualizer.tsx"
touch "src/presentation/components/features/audio-generation/ChunkList.tsx"
touch "src/presentation/components/features/audio-generation/ChunkPlayer.tsx"
touch "src/presentation/components/features/audio-generation/VoiceSelector.tsx"
touch "src/presentation/components/features/audio-generation/AudioControls.tsx"
touch "src/presentation/components/features/chat-interface/ChatContainer.tsx"
touch "src/presentation/components/features/chat-interface/MessageList.tsx"
touch "src/presentation/components/features/chat-interface/MessageBubble.tsx"
touch "src/presentation/components/features/chat-interface/ChatInput.tsx"
touch "src/presentation/components/features/chat-interface/StreamingMessage.tsx"
touch "src/presentation/components/features/chat-interface/ToolCallDisplay.tsx"
touch "src/presentation/components/features/chat-interface/WorkspacePanel.tsx"
touch "src/presentation/components/features/chat-interface/SessionHistory.tsx"
touch "src/presentation/components/features/error-management/ErrorList.tsx"
touch "src/presentation/components/features/error-management/ErrorDetails.tsx"
touch "src/presentation/components/features/error-management/RetryPanel.tsx"
touch "src/presentation/components/features/error-management/ErrorStats.tsx"
touch "src/presentation/components/features/settings/SettingsPanel.tsx"
touch "src/presentation/components/features/settings/PromptManager.tsx"
touch "src/presentation/components/features/settings/VoicePreferences.tsx"
touch "src/presentation/components/features/settings/ChannelSettings.tsx"
touch "src/presentation/components/shared/ui/Button.tsx"
touch "src/presentation/components/shared/ui/Input.tsx"
touch "src/presentation/components/shared/ui/Select.tsx"
touch "src/presentation/components/shared/ui/Table.tsx"
touch "src/presentation/components/shared/ui/Modal.tsx"
touch "src/presentation/components/shared/ui/Tabs.tsx"
touch "src/presentation/components/shared/ui/Card.tsx"
touch "src/presentation/components/shared/ui/Badge.tsx"
touch "src/presentation/components/shared/ui/Tooltip.tsx"
touch "src/presentation/components/shared/ui/Spinner.tsx"
touch "src/presentation/components/shared/layout/Header.tsx"
touch "src/presentation/components/shared/layout/Sidebar.tsx"
touch "src/presentation/components/shared/layout/Footer.tsx"
touch "src/presentation/components/shared/layout/Container.tsx"
touch "src/presentation/components/shared/feedback/Toast.tsx"
touch "src/presentation/components/shared/feedback/ProgressBar.tsx"
touch "src/presentation/components/shared/feedback/LoadingState.tsx"
touch "src/presentation/components/shared/feedback/EmptyState.tsx"
touch "src/presentation/components/shared/feedback/ErrorBoundary.tsx"
touch "src/presentation/components/shared/data/DataTable.tsx"
touch "src/presentation/components/shared/data/Pagination.tsx"
touch "src/presentation/components/shared/data/SearchBar.tsx"
touch "src/presentation/components/shared/data/FilterPanel.tsx"
touch "src/presentation/hooks/jobs/useJob.ts"
touch "src/presentation/hooks/jobs/useJobs.ts"
touch "src/presentation/hooks/jobs/useJobPolling.ts"
touch "src/presentation/hooks/jobs/useJobRealtime.ts"
touch "src/presentation/hooks/jobs/useCreateJob.ts"
touch "src/presentation/hooks/jobs/useRetryJob.ts"
touch "src/presentation/hooks/jobs/useCancelJob.ts"
touch "src/presentation/hooks/items/useContentItem.ts"
touch "src/presentation/hooks/items/useContentItems.ts"
touch "src/presentation/hooks/items/useItemPolling.ts"
touch "src/presentation/hooks/items/useRegenerateItem.ts"
touch "src/presentation/hooks/items/useItemActions.ts"
touch "src/presentation/hooks/streaming/useStreamingText.ts"
touch "src/presentation/hooks/streaming/useStreamingChat.ts"
touch "src/presentation/hooks/streaming/useSSE.ts"
touch "src/presentation/hooks/streaming/useStreamBuffer.ts"
touch "src/presentation/hooks/audio/useAudioPlayer.ts"
touch "src/presentation/hooks/audio/useAudioChunks.ts"
touch "src/presentation/hooks/audio/useWaveform.ts"
touch "src/presentation/hooks/audio/useVoices.ts"
touch "src/presentation/hooks/chat/useChatSession.ts"
touch "src/presentation/hooks/chat/useSendMessage.ts"
touch "src/presentation/hooks/chat/useChatHistory.ts"
touch "src/presentation/hooks/chat/useToolCalls.ts"
touch "src/presentation/hooks/csv/useCSVImport.ts"
touch "src/presentation/hooks/csv/useCSVValidation.ts"
touch "src/presentation/hooks/csv/useCSVPreview.ts"
touch "src/presentation/hooks/shared/useDebounce.ts"
touch "src/presentation/hooks/shared/useLocalStorage.ts"
touch "src/presentation/hooks/shared/usePagination.ts"
touch "src/presentation/hooks/shared/useFilters.ts"
touch "src/presentation/hooks/shared/useToast.ts"
touch "src/presentation/state/stores/uiStore.ts"
touch "src/presentation/state/stores/modalStore.ts"
touch "src/presentation/state/stores/sidebarStore.ts"
touch "src/presentation/state/queries/jobQueries.ts"
touch "src/presentation/state/queries/itemQueries.ts"
touch "src/presentation/state/queries/chunkQueries.ts"
touch "src/presentation/state/queries/chatQueries.ts"
touch "src/presentation/state/queries/voiceQueries.ts"
touch "src/presentation/state/queries/settingsQueries.ts"
touch "src/presentation/state/queries/queryClient.ts"
touch "src/shared/types/api.types.ts"
touch "src/shared/types/domain.types.ts"
touch "src/shared/types/dto.types.ts"
touch "src/shared/types/common.types.ts"
touch "src/shared/constants/statuses.ts"
touch "src/shared/constants/events.ts"
touch "src/shared/constants/errors.ts"
touch "src/shared/constants/queues.ts"
touch "src/shared/constants/api.ts"
touch "src/shared/utils/validation/validators.ts"
touch "src/shared/utils/validation/schemas.ts"
touch "src/shared/utils/formatting/date.ts"
touch "src/shared/utils/formatting/number.ts"
touch "src/shared/utils/formatting/text.ts"
touch "src/shared/utils/helpers/string.ts"
touch "src/shared/utils/helpers/array.ts"
touch "src/shared/utils/helpers/object.ts"
touch "src/shared/utils/errors/AppError.ts"
touch "src/shared/utils/errors/ErrorFactory.ts"
touch "src/shared/utils/errors/ErrorHandler.ts"
touch "src/shared/config/env.ts"
touch "src/shared/config/app.config.ts"
touch "src/shared/config/ai.config.ts"
touch "src/shared/config/tts.config.ts"
touch "src/shared/config/storage.config.ts"
touch "src/shared/lib/prisma.ts"
touch "src/shared/lib/logger.ts"
touch "src/shared/lib/monitoring.ts"